language: node_js
node_js:
  - "7"
dist: trusty
sudo: required
services:
  - docker
before_install:
  - docker pull concourse/concourse
  - docker pull postgres:9.5
script: npm test
notifications:
  email:
    on_success: never